### ISSUE TITLE
Error on composer install

### ISSUE THREAD

**Issue by bruli** [servergrove/KnowledgeBase#16]
Installing assets for Sensio\Bundle\DistributionBundle into web/bundles/sensiodistribution
Installing jackrabbit
Retrieving Jackrabbit from "http://apache.rediris.es/jackrabbit/2.4.3/jackrabbit-standalone-2.4.3.jar"
    Downloading: connection...
Retrieving Jackrabbit from "http://ftp.cixug.es/apache/jackrabbit/2.4.3/jackrabbit-standalone-2.4.3.jar"
    Downloading: connection...
Retrieving Jackrabbit from "http://www.eu.apache.org/dist/jackrabbit/2.4.3/jackrabbit-standalone-2.4.3.jar"
    Downloading: connection...
Retrieving Jackrabbit from "http://www.us.apache.org/dist/jackrabbit/2.4.3/jackrabbit-standalone-2.4.3.jar"
    Downloading: connection...
Script ServerGrove\KbBundle\Composer\JackrabbitInstaller::checkAndInstall handling the post-install-cmd event terminated with an exception

  [Exception]  
  Invalid file name  

Versión 2.4.3 don't exist.

**Comment by JMousqueton** [comment]
Any workarround for this issue ?

**Comment by pgodel** [comment]
Try updating the jackrabbit version to 2.4.5 and see if that works.

**Comment by gallart** [comment]
I can confirm the issue with 2.4.4 too.

Composer says to use dev-master for jackrabbit, how are we supposed to use a more recent version?

**Comment by gallart** [comment]
Workaround :

edit : src/ServerGrove/KbBundle/Composer/JackrabbitInstaller.php and change version to 2.4.5 on line 15.

I submitted a pull request about it.
