### ISSUE TITLE
Error 'Missing title' when adding new articles using Google Chrome

### ISSUE THREAD

**Issue by mstyne** [servergrove/KnowledgeBase#3]
Google Chrome 23.0.1271.95 on OS X encounters an issue when adding a new article. The POST to `check-article.json` fails with a 400 error.

[This Gist](https://gist.github.com/4219359) contains the output from `check-article.json`.

Firefox does not seem to encounter this problem; adding articles works fine in that browser.

Happy to assist with any additional troubleshooting.

**Comment by iambrosi** [comment]
This has been fixed. Thanks!
