### ISSUE TITLE
Error encountered after deleting a Category that contains articles

### ISSUE THREAD

**Issue by mstyne** [servergrove/KnowledgeBase#4]
After deleting a Category that contains existing articles, loading the 'Articles' section of the administrator interface fails with the following error:

```
[2012-12-05 17:53:02] request.CRITICAL: Twig_Error_Runtime: Item "getPath" for 
"" does not exist in "/opt/kb.local/src/ServerGrove/KbBundle/Resources/views/Admin/Articles/list.html.twig" 
at line 25 (uncaught exception) at /opt/kb.local/app/cache/dev/classes.php line 9302 [] []
```

My guess is the Article list is trying to load the details for the now nonexistent Category, which is leading to sadness.

**Comment by iambrosi** [comment]
@mstyne Can you confirm is working for you?

**Comment by mstyne** [comment]
Now of course it's up to you, but I think that removing the article wholesale from the system would be a somewhat unexpected behavior. Maybe the current system can't handle an article with no categories, I'm not sure.

This should probably resolve the issue I reported, but folks might not be too happy about their articles vanishing without them explicitly being removed. It could be that I'm misinterpreting what your change will actually do, however!

That said I'll be happy to test this particular change and let you know what I find out.

**Comment by mstyne** [comment]
I can confirm that this resolves the issue, however with the somewhat nasty side-effect of article deletion. I think your proposed change in #6 should do the trick though!
