### ISSUE TITLE
Issue handling ampersands (&) when using bold (**) and italic (*) Markdown syntax

### ISSUE THREAD

**Issue by mstyne** [servergrove/KnowledgeBase#9]
When editing an article in Markdown format, text entered like this:

**stop & go**

or

*stop & go*

will be displayed as

**stop &amp; go**

or

_stop &amp; go_

Ampersands written without bold or italic formatting do not have this issue.

Interestingly, the Preview pane renders the text correctly. I'm happy to research the issue further and submit a pull request if I can be pointed in the direction of where this is handled in the system.

Thanks!

**Comment by iambrosi** [comment]
@mstyne This issue is coming from the [KnpMarkdownBundle](https://github.com/KnpLabs/KnpMarkdownBundle). You can start by creating a test case that shows the error in their project.
